apiVersion: v1
kind: Secret
metadata:
  name: perchases-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
  API_KEY: {{ .Values.secret.API_KEY | quote }}

